#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - ru.patseev.helper.ktor.ru.patseev.helper.ktor.ApplicationJvmKt.moduleJvm
  logger: kmp