openapi: 3.0.4
info:
  title: "Marketplace ${VERSION_APP}"
  description: This is a place where worker can place an order for getting tools and see order status
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: order
    description: Заказ на выдачу инструмента
paths:
  /order/create:
    post:
      tags:
        - order
      summary: Create order
      operationId: orderCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreateResponse'
  /order/read:
    post:
      tags:
        - order
      summary: Read order
      operationId: orderRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderReadResponse'
  /order/update:
    post:
      tags:
        - order
      summary: Update order
      operationId: orderUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderUpdateResponse'
  /order/delete:
    post:
      tags:
        - order
      summary: Delete order
      operationId: orderDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDeleteResponse'
  /order/search:
    post:
      tags:
        - order
      summary: Search order
      operationId: orderSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderSearchResponse'

components:
  schemas:

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/OrderCreateRequest'
          read: '#/components/schemas/OrderReadRequest'
          update: '#/components/schemas/OrderUpdateRequest'
          delete: '#/components/schemas/OrderDeleteRequest'
          search: '#/components/schemas/OrderSearchRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/OrderCreateResponse'
          read: '#/components/schemas/OrderReadResponse'
          update: '#/components/schemas/OrderUpdateResponse'
          delete: '#/components/schemas/OrderDeleteResponse'
          search: '#/components/schemas/OrderSearchResponse'
          offers: '#/components/schemas/OrderOffersResponse'
          init: '#/components/schemas/OrderInitResponse'

    OrderId:
      type: string
      description: Идентификатор заказа

    TechnologyId:
      type: string
      description: Идентификатор технологии

    OperationId:
      type: string
      description: Идентификатор операции

    EmployeeId:
      type: string
      description: Идентификатор работника

    OperationStepId:
      type: string
      description: Идентификатор перехода

    OrderLock:
      type: string
      description: Версия оптимистичной блокировки

    Tool:
      type: object
      properties:
        toolCode:
          type: string
          description: Заводской уникальный шифр инструмента
          example: 2004-9060
        toolLife:
          type: integer
          description: стойкость инструмента
          example: 1800
        countCuttingEdge:
          type: integer
          description: количество режущих кромок
          example: 2
        info:
          type: string
          description: описание
          example: Пластина режущая
        toolType:
          $ref: '#/components/schemas/ToolType'

    ToolType:
      type: string
      description: Тип инструмента
      enum:
        - cutting
        - measuring
        - helper
        -
    ToolCodeAndCount:
      description: Словарь <Уникальный код инструмента, количество инструмента>
      type: object
      additionalProperties:
        type: integer
        format: int32

    OperationStep:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/OperationStepId'
        number:
          type: integer
          format: int32
          description: номер перехода
          example: 2
        operationId:
          $ref: '#/components/schemas/OperationId'
        duration:
          type: integer
          format: int32
          description: длительность в секундах
          example: 1200
        tools:
          type: array
          items:
            $ref: '#/components/schemas/Tool'

    Operation:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/OperationId'
        operationNumber:
          type: string
          description: номер операции
          example: 045
        operationType:
          $ref: '#/components/schemas/OperationType'
        technologyId:
          $ref: '#/components/schemas/TechnologyId'
        machine:
          type: string
          description: станок
        operationSteps:
          type: array
          items:
            $ref: '#/components/schemas/OperationStep'


    OperationType:
      type: string
      description: тип операции
      enum:
        - turning
        - milling
        - grinding
        - measuring

    BaseOrder:
      type: object
      description: Объект описывает свойства, одинаковые для create и update
      properties:
        operationId:
          $ref: '#/components/schemas/OperationId'
        employeeId:
          $ref: '#/components/schemas/EmployeeId'
        createTime:
          type: string
          description: Время создания/изменения заказа
        orderStatus:
          $ref: '#/components/schemas/OrderStatus'
        partCount:
          type: integer
          description: количество деталей

    OrderStatus:
      type: string
      description: 'Статус заказа'
      enum:
        - created
        - in progress
        - completed
        - finished

    OrderInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    OrderFinishResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    OrderCreateObject:
      allOf:
        - $ref: '#/components/schemas/BaseOrder'

    OrderCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/OrderRequestDebug'
        - type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderCreateObject'

    OrderReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/OrderId'

    OrderReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/OrderRequestDebug'
        - type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderReadObject'

    OrderUpdateObject:
      allOf:
        - $ref: '#/components/schemas/BaseOrder'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/OrderId'
            lock:
              $ref: '#/components/schemas/OrderLock'

    OrderUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/OrderRequestDebug'
        - type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderUpdateObject'

    OrderDeleteObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/OrderId'
            lock:
              $ref: '#/components/schemas/OrderLock'

    OrderDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/OrderRequestDebug'
        - type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderDeleteObject'

    OrderSearchFilter:
      type: object
      description: Набор фильтров для поиска
      properties:
        searchString:
          type: string
          description: Поисковая строка, которая будет искаться заказе

    OrderSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/OrderRequestDebug'
        - type: object
          properties:
            orderFilter:
              $ref: '#/components/schemas/OrderSearchFilter'


    OrderResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseOrder'
        - type: object
          description: Объект, который возвращается в ответе бэкенда
          properties:
            id:
              $ref: '#/components/schemas/OrderId'
            tools:
                $ref: '#/components/schemas/ToolCodeAndCount'
            missingTools:
                $ref: '#/components/schemas/ToolCodeAndCount'
            lock:
              $ref: '#/components/schemas/OrderLock'
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/OrderPermissions'

    OrderPermissions:
      type: string
      description: Доступы для клиента для операций над объявлением
      enum:
        - read
        - update
        - delete
        - changeStatus

    OrderResponseSingle:
      allOf:
        - type: object
          description: Ответ с одним объектом объявления
          properties:
            order:
              $ref: '#/components/schemas/OrderResponseObject'

    OrderResponseMulti:
      allOf:
        - type: object
          description: Список найденных объектов
          properties:
            orders:
              type: array
              items:
                $ref: '#/components/schemas/OrderResponseObject'

    OrderCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseSingle'

    OrderReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseSingle'

    OrderUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseSingle'

    OrderDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseSingle'

    OrderSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseMulti'

    OrderOffersResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/OrderResponseSingle'
        - $ref: '#/components/schemas/OrderResponseMulti'

    # STUBS ======================
    OrderRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    OrderRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/OrderDebug'

    OrderDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/OrderRequestDebugMode'
        stub:
          $ref: '#/components/schemas/OrderRequestDebugStubs'

    OrderRequestDebugStubs:
      type: string
      description: Перечисления всех стабов
      enum:
        - success
        - notFound
        - badId
        - cannotDelete
        - badSearchString
